name: "Codecheck"
description: "AI-powered code review using OpenAI GPT models"

inputs:
  openai_api_key:
    description: "OpenAI API key"
    required: true
  openai_model:
    description: "OpenAI model to use (default: gpt-4o)"
    required: false
    default: "gpt-4o"
  exclude:
    description: "Comma-separated list of file patterns to exclude"
    required: false
    default: "**/*.json, **/*.md"

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Codecheck
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        OPENAI_API_MODEL: ${{ inputs.openai_model }}
        EXCLUDE_PATTERNS: ${{ inputs.exclude }}
      run: python src/main.py
